#include "iostream"
#include "time.h"
#include "string"
#include "cstdlib"
#include "ctime"


using namespace std;
int RESTART()
{
	srand((unsigned)time(0));
	string A0, A1, A2;
	int NGuess = 0;
	int Guess;
	int RN =  (rand()%100)+1;
	int Iscore = 200;
	// while loop of the game
	while (Guess != RN)
	{
		//Typing the guess
		cout << "\nYour guess: ";
		cin >> Guess;
		while(!cin.good())
{
		cin.clear();
		cin.ignore(INT_MAX, '\n');
		cout << "A Number!: ";
		cin >> Guess;//ask again
}
//verifies if the number typed is between 1 and 100
		if(Guess > 100 || Guess < 1)
		 {
			cout << "Wow chill dude, type a number between 100 and 1 (inlucing 100 and 1)\n";
			Guess = 1;
		 }

//if Guess is bigger than the random number
		else if(Guess > RN )
		 {
			cout << "You need to pick a Smaller number\n";
			NGuess += 1;
		}

//if Guess is smaller than the Random number
		else if(Guess < RN )
		 {
			cout << "You need to pick a Bigger number\n";
			NGuess += 1;
		 }

//If Guess is equal to the Random number
		if(Guess == RN)
		 {

			cout << "\nI mean ... You got it right. Well played.";
			cout << "\nYou used " << NGuess <<" Guesses\n";
			cout << "So your score is "<< Iscore - (NGuess*10)<< endl;
			cout << "Do you want to replay?\n[Y for yes, and anything for No]\n";
			cin >> A2;
			if(A2 == "Y" || A2 == "y")
		 	 {
				RESTART();
			 }
			else
			 {
				cout << "\nSee ya";
			}//else
		 }// if
	}// while loop}
}


int main()
{
	// variables
	srand((unsigned)time(0));
	string A0, A1,A2;
	int NGuess = 0;
	int Guess;
	int RN =  (rand()%100)+1;
	int Iscore = 200;
	string Name;

	//Game's start
	cout << "Hey, WELCOME to a pretty simple game\n"
		"Do you want to know the rules?\n"
		"[To know the rules type Y, if you want to pass just type anything else]\n";
	cin >> A0;

	if (A0 == "Y" || A0 == "y")
	{
		cout << "\nNice so the goal is simple, you need to find a random number generated by Myself \n"
			"between 1 and 100 (including 1 and 100), you need to find it in the least amount of guesses\n"
			"so you get a better score.\n";
	}

	else
	{
		cout << "\nOkay so let's start!\n";
	}

	cout << "\nSo ... wait, I beg your pardon, but I forgot to ask for your name.\n Could I by any chance get your name?"
		"['Y' for Yes, anything else for No]\n";
	cin >> A1;

	if (A1 == "Y"||A1== "y")
	{
		cout << "\nSweet ~(^-^)~\n";
	}

	else
	{
		cout << "\nOkay :'(, I ain't playing with you unless you give me a name\n";
	}

	cout << "\nName: ";
	cin >> Name;
	cout << "\nSo let's begin " << Name << endl;
	cout << "Hmmmm";
	cout << " Okay!!! I came up with a number, my favorite one. I mean they are all my favorite ones.\n";

	// while loop of the game
	while (Guess != RN)
	{
		//Typing the guess
		cout << "\nYour guess: ";
		cin >> Guess;
		while(!cin.good())
{
    cin.clear();
    cin.ignore(INT_MAX, '\n');
		cout << "A Number!: ";
    cin >> Guess;//ask again
}
//verifies if the number typed is between 1 and 100
		if(Guess > 100 || Guess < 1)
		 {
			cout << "Wow chill dude, type a number between 100 and 1 (inlucing 100 and 1)\n";
			Guess = 1;
		 }

//if Guess is bigger than the random number
		else if(Guess > RN )
		 {
			cout << "You need to pick a Smaller number\n";
			NGuess += 1;
		}

//if Guess is smaller than the Random number
		else if(Guess < RN )
		 {
			cout << "You need to pick a Bigger number\n";
			NGuess += 1;
		 }

//If Guess is equal to the Random number
		if(Guess == RN)
		 {

			cout << "\nI mean ... You got it right. Well played.";
			cout << "\nYou used " << NGuess <<" Guesses\n";
			cout << "So your score is "<< Iscore - (NGuess*10)<< endl;
			cout << "Do you want to replay?\n[Y for yes, and anything for No]\n";
			cin >> A2;
			if(A2 == "Y" || A2 == "y")
		 	 {
				RESTART();
			 }
			else
			 {
				cout << "\nSee ya";
			}//else
		 }// if
	}// while loop
}// main function
